require("settings")
require("packages.packer")
require("packages.treesitter")
require("packages.theme")
require("packages.lspconfig")
require("packages.cmp")
require("packages.cmp-git")
require("packages.telescope")
-- require("packages.autopairs")
require("packages.comment")
require("packages.vm")
require("packages.nvim-tree")
require("packages.neoformat")
require("packages.spellsitter")
require("custom.swap-buffer")
require("mapping")
